print("Jack and Jill went up the hill")
print("To fetch a pail of water.")
print("Jack fell down and broke his crown,")
print("And Jill came tumbling after.")
print("Then up got Jack and said to Jill,")
print("As in his arms he took her,")
print("“Brush off that dirt for you’re not hurt,")
print("Let’s fetch that pail of water.”")
print("So Jack and Jill went up the hill")
print("To fetch the pail of water,")
print("And took it home to Mother dear,")
print("Who thanked her son and daughter.\nscsc sacsacew edw")
